global_frame: map
rolling_window: false
track_unknown_space: true
#publish_frequency: 1.0
#update_frequency: 2.0


plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
#  - {name: prohibition,               type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}



#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true, max_obstacle_height: 0.8}

inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 0.5

prohibition:
    prohibition_areas:
      [[[-8, -1.25],[-1, -1.25],[-1, 1.25],[-8, 1.25]], [[10, -1.25],[1, -1.25],[1, 1.25],[10, 1.25]]]
